language: node_js

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - '8'

script:
  - yarn build
  - yarn sw
  - yarn lint

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master